require("core.plugin_config.nightfox")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.mason")
require("core.plugin_config.lsp")
--require("core.plugin_config.nvim-tree")
--require("core.plugin_config.dashboard")
--require("core.plugin_config.lualine")
